# Generated by Django 5.0.6 on 2024-06-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_shoppingcart_options_shoppingcart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.shoppingcart', verbose_name='Список товара'),
            preserve_default=False,
        ),
    ]
