# Generated by Django 5.0.6 on 2024-06-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_shoppingcart_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cartItems',
        ),
    ]
