# Generated by Django 5.0.6 on 2024-06-08 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(null=True, upload_to='pictures/categories/images', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
